services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - webnet
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - webnet
    restart: always

networks:
  webnet:
